// required: associates our `main.dart` with the code generated by Freezed
import 'package:freezed_annotation/freezed_annotation.dart';

part 'media.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'media.g.dart';

@freezed
abstract class TemporaryMedia with _$TemporaryMedia {
  const factory TemporaryMedia({
    required int id,
    @JsonKey(name: 'thumb_url') String? thumbUrl,
    required String url,
  }) = _TemporaryMedia;

  factory TemporaryMedia.fromJson(Map<String, Object?> json) =>
      _$TemporaryMediaFromJson(json);
}
