// required: associates our `main.dart` with the code generated by Freezed

import 'package:freezed_annotation/freezed_annotation.dart';



part 'media.freezed.dart';

part 'media.g.dart';



/// JSON / 业务侧 id 可为 int 或 String（如低代码槽位 id、上传后的媒体 id）。

Object temporaryMediaIdFromJson(dynamic value) {

  if (value == null) {

    throw ArgumentError('TemporaryMedia.id is required');

  }

  if (value is int) return value;

  if (value is String) return value;

  if (value is num) return value.toInt();

  return value.toString();

}



dynamic temporaryMediaIdToJson(Object id) {

  if (id is int) return id;

  if (id is String) {

    final parsed = int.tryParse(id);

    return parsed ?? id;

  }

  if (id is num) return id.toInt();

  return id.toString();

}



@freezed

abstract class TemporaryMedia with _$TemporaryMedia {

  const TemporaryMedia._();



  const factory TemporaryMedia({

    @JsonKey(fromJson: temporaryMediaIdFromJson, toJson: temporaryMediaIdToJson)

    required Object id,

    String? uuid,

    @JsonKey(name: 'thumb_url') String? thumbUrl,

    required String url,

  }) = _TemporaryMedia;



  factory TemporaryMedia.fromJson(Map<String, Object?> json) =>

      _$TemporaryMediaFromJson(json);



  String get idAsString => id.toString();



  int? get idAsInt {

    if (id is int) return id as int;

    if (id is num) return (id as num).toInt();

    if (id is String) return int.tryParse(id as String);

    return int.tryParse(id.toString());

  }



  bool idEquals(dynamic other) {

    if (other == null) return false;

    return id.toString() == other.toString();

  }

}

